#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH

build_tsc() {
    set -x
    rm -rfv dist
    cp -rfv src dist
    cat tsconfig.json | jq 'del(.include, .compilerOptions.outDir)' >dist/tsconfig.json
    cp -v README.md LICENSE package.json dist
    cd dist
    /usr/bin/find -name '*.spec.ts' | xargs rm -rvf
    tsc -p .
    rm -rvf tsconfig.json
    cd ..
    set +x
}

build() {
    set -x
    rm -rfv dist
    # npm i tsup --no-save on CI/CD
    npx tsup src/index.ts --format cjs --target es2020 --sourcemap --dts
    cp -fv README.md LICENSE package.json dist
}

"$@"
