#!/bin/bash
PATH="$PWD/node_modules/.bin":$PATH

hello() {
    echo Hello from taskfile
    echo args: "$1" "$2" "$3"
}

build() {
    set -x
    rm -rfv dist
    cp -rfv src dist
    cat tsconfig.json | jq 'del(.include, .compilerOptions.outDir)' > dist/tsconfig.json
    cp -v README.md LICENSE package.json dist
    cd dist
    /usr/bin/find -name '*.spec.ts' | xargs rm -rvf
    tsc -p .
    rm -rvf tsconfig.json
    cd ..
    set +x
}

build_bundle() {
    set -x
    rm -rfv dist
    cp -rfv src dist
    cat tsconfig.json | jq 'del(.include, .compilerOptions.outDir)' > dist/tsconfig.json
    cp -v README.md LICENSE package.json dist
    cd dist
    /usr/bin/find -name '*.spec.ts' | xargs rm -rvf
    npx typescript-bundle tsconfig.json --entryPoint index --exportAs commonjs --outFile index.js
    rm -rvf tsconfig.json
    /usr/bin/find -name '*.ts' | xargs rm -rvf
    /usr/bin/find . -type d -empty -delete
    cd ..
    set +x
}

"$@"
